### ISSUE TITLE
Summarise //TODO comments on develop

### ISSUE THREAD

**Issue by theLAZYmd** [andreeaionescu/etudiweb#17]
- [ ] Finalise data structure for a Pinned item
- [ ] Define data, articles, and receiveError types for searchArticles.ts
- [ ] Confirm types for mapDispatchToProps and other redux functions because they're quite complicated
- [ ] Proper dispatching for new pinboard functions
